### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [firebearstudio/ConfigurableProducts#2]
Please make changes to composer.json to require php7 as well:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - firebear/configurableproducts dev-master requires php ~5.5.0|~5.6.0 -> your PHP version does not satisfy that requirement.
    - firebear/configurableproducts dev-master requires php ~5.5.0|~5.6.0 -> your PHP version does not satisfy that requirement.
    - firebear/configurableproducts dev-master requires php ~5.5.0|~5.6.0 -> your PHP version does not satisfy that requirement.
    - Installation request for firebear/configurableproducts dev-master -> satisfiable by firebear/configurableproducts[dev-master].

Removal failed, reverting ./composer.json to its original content.

**Comment by pixelpusher81** [comment]
Same issue:

Loading composer repositories with package information        
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

Problem 1
- firebear/configurableproducts dev-master requires php ~5.5.0|~5.6.0 -> your PHP version does not satisfy that requirement.
- firebear/configurableproducts dev-master requires php ~5.5.0|~5.6.0 -> your PHP version does not satisfy that requirement.
- Installation request for firebear/configurableproducts dev-master -> satisfiable by firebear/configurableproducts[dev-master].

**Comment by adamj88** [comment]
I'm having same problem - unable to install this when using M2 with php v7 as per their system requirements.

Presume the `composer.json` file is outdated.

@nikolaevas would you been open for me to submit a PR to rectify this?

**Comment by biotech** [comment]
Fix merged. Thanks
